### ISSUE TITLE
USER STORY: Get information about costs or ask other questions

### ISSUE THREAD

**Issue by Sndrahel** [Sndrahel/Handywoman#9]
As a **Site User** I want to be able to **get a quotation for service**, so that I can **get information about costs or ask other questions**

# Acceptance Criteria:

* Acceptance Criteria 1: User will be able to navigate to a contact page
* Acceptance Criteria 2: User can then complete the contact/request form and submit it

# Tasks:

- [x] Task 1: Configure the required view in Django
- [x] Task 2: Configure the required template
- [x] Task 3: Configure the required URL
